apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest   # ❌ latest tag (bad practice)
    ports:
    - containerPort: 80

    securityContext:
      privileged: true    # ❌ very dangerous

    env:
    - name: PASSWORD
      value: "admin123"   # ❌ hardcoded secret

    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "0"          # ❌ wrong config
